set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_mig_7series_0_3/dyract_sys_mig_7series_0_3/user_design/constraints/dyract_sys_mig_7series_0_3.xdc rfile:../../../dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_mig_7series_0_3/dyract_sys_mig_7series_0_3/user_design/constraints/dyract_sys_mig_7series_0_3.xdc id:1 order:EARLY scoped_inst:dyract_sys_i/mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/pcie_7x_0/source/pcie_7x_0-PCIE_X1Y0.xdc rfile:../../../dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/pcie_7x_0/source/pcie_7x_0-PCIE_X1Y0.xdc id:2 order:EARLY scoped_inst:dyract_sys_i/dyract_0/inst/pcie/pcie_7x_v1_8_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.srcs/sources_1/ipshared/VIP/dyract_v1_1/034c9e85/src/dyract.xdc rfile:../../../dyract_in_sys.srcs/sources_1/ipshared/VIP/dyract_v1_1/034c9e85/src/dyract.xdc id:3 order:EARLY scoped_inst:dyract_sys_i/dyract_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.srcs/constrs_1/new/dytact_sys.xdc rfile:../../../dyract_in_sys.srcs/constrs_1/new/dytact_sys.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.runs/synth_1/dont_touch.xdc rfile:../dont_touch.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo_clocks.xdc rfile:../../../dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo_clocks.xdc id:6 order:LATE scoped_inst:dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_wr_fifo_1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo_clocks.xdc rfile:../../../dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo_clocks.xdc id:7 order:LATE scoped_inst:dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_wr_fifo_2/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/kizheppa/dyract_in_sys/dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo_clocks.xdc rfile:../../../dyract_in_sys.srcs/sources_1/bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo_clocks.xdc id:8 order:LATE scoped_inst:dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_rd_fifo/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:730 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:731 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:733 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y23 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:735 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y22 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y21 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:737 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:738 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:SCOPED_XDC file:1 line:742 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:743 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:744 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:749 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:750 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:SCOPED_XDC file:1 line:756 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:758 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y23 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y22 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:762 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y21 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:763 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y19 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:769 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y18 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:770 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y17 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y16 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y27 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y26 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y25 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:775 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y24 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:SCOPED_XDC file:1 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:778 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:779 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:SCOPED_XDC file:1 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y4 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y5 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:783 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y6 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:SCOPED_XDC file:1 line:785 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y243 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y231 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:787 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y219 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y207 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:789 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y343 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y331 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:791 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y319 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y307 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:SCOPED_XDC file:1 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y5 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:SCOPED_XDC file:1 line:795 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y5 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:SCOPED_XDC file:1 line:822 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_property src_info {type:SCOPED_XDC file:1 line:823 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:SCOPED_XDC file:1 line:827 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y11 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y10 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y9 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y8 [get_cells {inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_X1Y0 [get_cells inst/pcie_top_i/pcie_7x_i/pcie_block_i]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X14Y25 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X13Y26 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X13Y25 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X13Y24 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X13Y23 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X13Y22 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X13Y21 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X13Y20 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y5 [get_cells pcie/refclk_ibuf];
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0_0 ila
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/clk [get_nets [list dyract_sys_i/dyract_0/inst/pcie/PIPE_USERCLK2_IN]]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe0]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe0 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/app/rx_engine/m_axis_rx_tready0]]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1_0 ila
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1_0]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/clk]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/clk [get_nets [list dyract_sys_i/mig_7series_0_ui_clk]]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1_0/probe0]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe0 [get_nets [list {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[0]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[1]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[2]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[3]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[4]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[5]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[6]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[7]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[8]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[9]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[10]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[11]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[12]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[13]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[14]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[15]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[16]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[17]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[18]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[19]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[20]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[21]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[22]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[23]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[24]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[25]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[26]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[27]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[28]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[29]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[30]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARADDR[31]}]]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe1]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe1 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/m_axis_rx_tvalid]]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe2]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe2 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/app/rx_engine/rcvd_data_valid_o0]]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe3]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe3 [get_nets [list dyract_sys_i/dyract_0/inst/sys_user_dma_en]]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe4]
set_property src_info {type:XDC file:4 line:51 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe4 [get_nets [list dyract_sys_i/dyract_0/inst/user_sys_dma_en]]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe5]
set_property src_info {type:XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe5 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/app/intr_done]]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe6]
set_property src_info {type:XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe6 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/app/intr_req]]
set_property src_info {type:XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe7]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe7 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/app/reg_file/intr_state]]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe8]
set_property src_info {type:XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe8 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/pcie_7x_v1_8_i/cfg_interrupt_msienable]]
set_property src_info {type:XDC file:4 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:4 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe9]
set_property src_info {type:XDC file:4 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe9 [get_nets [list dyract_sys_i/dyract_0/inst/pcie/pcie_7x_v1_8_i/cfg_interrupt_msixenable]]
set_property src_info {type:XDC file:4 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_1_0/probe1]
set_property src_info {type:XDC file:4 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe1 [get_nets [list {dyract_sys_i/dyract_0_m_axi_mm2s_ARBURST[0]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARBURST[1]}]]
set_property src_info {type:XDC file:4 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_1_0/probe2]
set_property src_info {type:XDC file:4 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe2 [get_nets [list {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[0]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[1]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[2]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[3]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[4]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[5]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[6]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARLEN[7]}]]
set_property src_info {type:XDC file:4 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_1_0/probe3]
set_property src_info {type:XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe3 [get_nets [list {dyract_sys_i/dyract_0_m_axi_mm2s_ARSIZE[0]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARSIZE[1]} {dyract_sys_i/dyract_0_m_axi_mm2s_ARSIZE[2]}]]
set_property src_info {type:XDC file:4 line:76 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_1_0/probe4]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe4 [get_nets [list {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[0]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[1]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[2]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[3]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[4]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[5]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[6]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[7]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[8]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[9]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[10]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[11]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[12]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[13]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[14]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[15]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[16]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[17]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[18]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[19]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[20]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[21]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[22]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[23]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[24]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[25]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[26]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[27]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[28]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[29]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[30]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[31]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[32]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[33]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[34]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[35]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[36]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[37]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[38]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[39]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[40]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[41]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[42]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[43]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[44]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[45]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[46]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[47]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[48]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[49]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[50]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[51]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[52]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[53]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[54]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[55]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[56]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[57]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[58]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[59]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[60]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[61]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[62]} {dyract_sys_i/dyract_0_m_axi_mm2s_RDATA[63]}]]
set_property src_info {type:XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_1_0/probe5]
set_property src_info {type:XDC file:4 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe5 [get_nets [list {dyract_sys_i/dyract_0_m_axi_mm2s_RRESP[0]} {dyract_sys_i/dyract_0_m_axi_mm2s_RRESP[1]}]]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_1_0/probe6]
set_property src_info {type:XDC file:4 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe6 [get_nets [list {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[0]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[1]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[2]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[3]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[4]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[5]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[6]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[7]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[8]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[9]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[10]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[11]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[12]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[13]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[14]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[15]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[16]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[17]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[18]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[19]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[20]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[21]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[22]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[23]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[24]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[25]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[26]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[27]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[28]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[29]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[30]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWADDR[31]}]]
set_property src_info {type:XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_1_0/probe7]
set_property src_info {type:XDC file:4 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe7 [get_nets [list {dyract_sys_i/dyract_0_m_axi_s2mm_AWBURST[0]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWBURST[1]}]]
set_property src_info {type:XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_1_0/probe8]
set_property src_info {type:XDC file:4 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe8 [get_nets [list {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[0]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[1]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[2]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[3]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[4]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[5]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[6]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWLEN[7]}]]
set_property src_info {type:XDC file:4 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_1_0/probe9]
set_property src_info {type:XDC file:4 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe9 [get_nets [list {dyract_sys_i/dyract_0_m_axi_s2mm_AWSIZE[0]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWSIZE[1]} {dyract_sys_i/dyract_0_m_axi_s2mm_AWSIZE[2]}]]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_1_0/probe10]
set_property src_info {type:XDC file:4 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe10 [get_nets [list {dyract_sys_i/dyract_0_m_axi_s2mm_BRESP[0]} {dyract_sys_i/dyract_0_m_axi_s2mm_BRESP[1]}]]
set_property src_info {type:XDC file:4 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_1_0/probe11]
set_property src_info {type:XDC file:4 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe11 [get_nets [list {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[0]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[1]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[2]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[3]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[4]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[5]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[6]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[7]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[8]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[9]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[10]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[11]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[12]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[13]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[14]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[15]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[16]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[17]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[18]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[19]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[20]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[21]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[22]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[23]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[24]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[25]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[26]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[27]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[28]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[29]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[30]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[31]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[32]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[33]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[34]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[35]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[36]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[37]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[38]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[39]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[40]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[41]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[42]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[43]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[44]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[45]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[46]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[47]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[48]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[49]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[50]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[51]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[52]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[53]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[54]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[55]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[56]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[57]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[58]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[59]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[60]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[61]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[62]} {dyract_sys_i/dyract_0_m_axi_s2mm_WDATA[63]}]]
set_property src_info {type:XDC file:4 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_1_0/probe12]
set_property src_info {type:XDC file:4 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe12 [get_nets [list {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[0]} {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[1]} {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[2]} {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[3]} {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[4]} {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[5]} {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[6]} {dyract_sys_i/dyract_0_m_axi_s2mm_WSTRB[7]}]]
set_property src_info {type:XDC file:4 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe13]
set_property src_info {type:XDC file:4 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe13 [get_nets [list dyract_sys_i/dyract_0_m_axi_mm2s_ARREADY]]
set_property src_info {type:XDC file:4 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe14]
set_property src_info {type:XDC file:4 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe14 [get_nets [list dyract_sys_i/dyract_0_m_axi_mm2s_ARVALID]]
set_property src_info {type:XDC file:4 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe15]
set_property src_info {type:XDC file:4 line:111 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe15 [get_nets [list dyract_sys_i/dyract_0_m_axi_mm2s_RLAST]]
set_property src_info {type:XDC file:4 line:112 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe16]
set_property src_info {type:XDC file:4 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe16 [get_nets [list dyract_sys_i/dyract_0_m_axi_mm2s_RREADY]]
set_property src_info {type:XDC file:4 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe17]
set_property src_info {type:XDC file:4 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe17 [get_nets [list dyract_sys_i/dyract_0_m_axi_mm2s_RVALID]]
set_property src_info {type:XDC file:4 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe18]
set_property src_info {type:XDC file:4 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe18 [get_nets [list dyract_sys_i/dyract_0_m_axi_s2mm_AWREADY]]
set_property src_info {type:XDC file:4 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe19]
set_property src_info {type:XDC file:4 line:123 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe19 [get_nets [list dyract_sys_i/dyract_0_m_axi_s2mm_AWVALID]]
set_property src_info {type:XDC file:4 line:124 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe20]
set_property src_info {type:XDC file:4 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe20 [get_nets [list dyract_sys_i/dyract_0_m_axi_s2mm_BREADY]]
set_property src_info {type:XDC file:4 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe21]
set_property src_info {type:XDC file:4 line:129 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe21 [get_nets [list dyract_sys_i/dyract_0_m_axi_s2mm_BVALID]]
set_property src_info {type:XDC file:4 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe22]
set_property src_info {type:XDC file:4 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe22 [get_nets [list dyract_sys_i/dyract_0_m_axi_s2mm_WLAST]]
set_property src_info {type:XDC file:4 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe23]
set_property src_info {type:XDC file:4 line:135 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe23 [get_nets [list dyract_sys_i/dyract_0_m_axi_s2mm_WREADY]]
set_property src_info {type:XDC file:4 line:136 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1_0 probe
set_property src_info {type:XDC file:4 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1_0/probe24]
set_property src_info {type:XDC file:4 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1_0/probe24 [get_nets [list dyract_sys_i/dyract_0_m_axi_s2mm_WVALID]]
set_property src_info {type:XDC file:4 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_PIPE_USERCLK2_IN]
set_property src_info {type:XDC file:5 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_buffer || ORIG_REF_NAME==config_buffer}]
set_property src_info {type:XDC file:5 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==config_buffer || ORIG_REF_NAME==config_buffer}] {/U0 }]/U0 ]]
set_property src_info {type:SCOPED_XDC file:6 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_wr_fifo_1/inst/m_axis_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_wr_fifo_1/inst/s_axis_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_wr_fifo_2/inst/m_axis_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_wr_fifo_2/inst/s_axis_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_rd_fifo/inst/m_axis_aclk]]]
set_property src_info {type:SCOPED_XDC file:8 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]] -to [get_cells gen_fifo_generator.fifo_generator_inst/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins dyract_sys_i/dyract_0/inst/pcie/app/psg1/user_rd_fifo/inst/s_axis_aclk]]]
