# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dytact_sys.xdc

# Block Designs: bd/dyract_sys/dyract_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys || ORIG_REF_NAME==dyract_sys}]

# IP: bd/dyract_sys/ip/dyract_sys_microblaze_0_1/dyract_sys_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_microblaze_0_1 || ORIG_REF_NAME==dyract_sys_microblaze_0_1}]

# IP: bd/dyract_sys/ip/dyract_sys_dlmb_v10_1/dyract_sys_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_dlmb_v10_1 || ORIG_REF_NAME==dyract_sys_dlmb_v10_1}]

# IP: bd/dyract_sys/ip/dyract_sys_ilmb_v10_1/dyract_sys_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_ilmb_v10_1 || ORIG_REF_NAME==dyract_sys_ilmb_v10_1}]

# IP: bd/dyract_sys/ip/dyract_sys_dlmb_bram_if_cntlr_1/dyract_sys_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==dyract_sys_dlmb_bram_if_cntlr_1}]

# IP: bd/dyract_sys/ip/dyract_sys_ilmb_bram_if_cntlr_1/dyract_sys_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==dyract_sys_ilmb_bram_if_cntlr_1}]

# IP: bd/dyract_sys/ip/dyract_sys_lmb_bram_1/dyract_sys_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_lmb_bram_1 || ORIG_REF_NAME==dyract_sys_lmb_bram_1}]

# IP: bd/dyract_sys/ip/dyract_sys_mdm_1_1/dyract_sys_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_mdm_1_1 || ORIG_REF_NAME==dyract_sys_mdm_1_1}]

# IP: bd/dyract_sys/ip/dyract_sys_mig_7series_0_3/dyract_sys_mig_7series_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_mig_7series_0_3 || ORIG_REF_NAME==dyract_sys_mig_7series_0_3}]

# IP: bd/dyract_sys/ip/dyract_sys_axi_mem_intercon_0/dyract_sys_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_axi_mem_intercon_0 || ORIG_REF_NAME==dyract_sys_axi_mem_intercon_0}]

# IP: bd/dyract_sys/ip/dyract_sys_xbar_1/dyract_sys_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_xbar_1 || ORIG_REF_NAME==dyract_sys_xbar_1}]

# IP: bd/dyract_sys/ip/dyract_sys_rst_mig_7series_0_100M_1/dyract_sys_rst_mig_7series_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_rst_mig_7series_0_100M_1 || ORIG_REF_NAME==dyract_sys_rst_mig_7series_0_100M_1}]

# IP: bd/dyract_sys/ip/dyract_sys_dyract_0_1/dyract_sys_dyract_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_dyract_0_1 || ORIG_REF_NAME==dyract_sys_dyract_0_1}]

# IP: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==user_fifo || ORIG_REF_NAME==user_fifo}]

# IP: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/axi_datamover_0/axi_datamover_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_datamover_0 || ORIG_REF_NAME==axi_datamover_0}]

# IP: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/pcie_7x_0/pcie_7x_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0}]

# IP: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/config_buffer/config_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==config_buffer || ORIG_REF_NAME==config_buffer}]

# IP: bd/dyract_sys/ip/dyract_sys_auto_us_0/dyract_sys_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_0 || ORIG_REF_NAME==dyract_sys_auto_us_0}]

# IP: bd/dyract_sys/ip/dyract_sys_auto_us_1/dyract_sys_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_1 || ORIG_REF_NAME==dyract_sys_auto_us_1}]

# IP: bd/dyract_sys/ip/dyract_sys_auto_pc_0/dyract_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_auto_pc_0 || ORIG_REF_NAME==dyract_sys_auto_pc_0}]

# IP: bd/dyract_sys/ip/dyract_sys_auto_us_2/dyract_sys_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_2 || ORIG_REF_NAME==dyract_sys_auto_us_2}]

# IP: bd/dyract_sys/ip/dyract_sys_auto_us_3/dyract_sys_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_3 || ORIG_REF_NAME==dyract_sys_auto_us_3}]

# IP: bd/dyract_sys/ip/dyract_sys_auto_us_4/dyract_sys_auto_us_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_4 || ORIG_REF_NAME==dyract_sys_auto_us_4}]

# XDC: bd/dyract_sys/ip/dyract_sys_microblaze_0_1/dyract_sys_microblaze_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_microblaze_0_1 || ORIG_REF_NAME==dyract_sys_microblaze_0_1}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_microblaze_0_1/dyract_sys_microblaze_0_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_dlmb_v10_1/dyract_sys_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_dlmb_v10_1 || ORIG_REF_NAME==dyract_sys_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dlmb_v10_1/dyract_sys_dlmb_v10_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_ilmb_v10_1/dyract_sys_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_ilmb_v10_1 || ORIG_REF_NAME==dyract_sys_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_ilmb_v10_1/dyract_sys_ilmb_v10_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_dlmb_bram_if_cntlr_1/dyract_sys_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_ilmb_bram_if_cntlr_1/dyract_sys_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_lmb_bram_1/dyract_sys_lmb_bram_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_mdm_1_1/dyract_sys_mdm_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_mdm_1_1 || ORIG_REF_NAME==dyract_sys_mdm_1_1}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_mdm_1_1/dyract_sys_mdm_1_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_mig_7series_0_3/dyract_sys_mig_7series_0_3/user_design/constraints/dyract_sys_mig_7series_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_mig_7series_0_3 || ORIG_REF_NAME==dyract_sys_mig_7series_0_3}]

# XDC: bd/dyract_sys/ip/dyract_sys_mig_7series_0_3/dyract_sys_mig_7series_0_3/user_design/constraints/dyract_sys_mig_7series_0_3_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_mig_7series_0_3/dyract_sys_mig_7series_0_3_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_mig_7series_0_3 || ORIG_REF_NAME==dyract_sys_mig_7series_0_3}]

# XDC: bd/dyract_sys/ip/dyract_sys_xbar_1/dyract_sys_xbar_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_rst_mig_7series_0_100M_1/dyract_sys_rst_mig_7series_0_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_rst_mig_7series_0_100M_1 || ORIG_REF_NAME==dyract_sys_rst_mig_7series_0_100M_1}]

# XDC: bd/dyract_sys/ip/dyract_sys_rst_mig_7series_0_100M_1/dyract_sys_rst_mig_7series_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dyract_sys_rst_mig_7series_0_100M_1 || ORIG_REF_NAME==dyract_sys_rst_mig_7series_0_100M_1}]

# XDC: bd/dyract_sys/ip/dyract_sys_rst_mig_7series_0_100M_1/dyract_sys_rst_mig_7series_0_100M_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==user_fifo || ORIG_REF_NAME==user_fifo}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/user_fifo/user_fifo/user_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==user_fifo || ORIG_REF_NAME==user_fifo}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/axi_datamover_0/axi_datamover_0_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/axi_datamover_0/axi_datamover_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_0 || ORIG_REF_NAME==axi_datamover_0}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/axi_datamover_0/axi_datamover_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_datamover_0 || ORIG_REF_NAME==axi_datamover_0}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/pcie_7x_0/source/pcie_7x_0-PCIE_X1Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0 || ORIG_REF_NAME==pcie_7x_0}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/pcie_7x_0/synth/pcie_7x_0_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/config_buffer/config_buffer/config_buffer_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==config_buffer || ORIG_REF_NAME==config_buffer}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/config_buffer/config_buffer/config_buffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==config_buffer || ORIG_REF_NAME==config_buffer}] {/U0 }]/U0 ]]

# XDC: bd/dyract_sys/ip/dyract_sys_dyract_0_1/src/config_buffer/config_buffer_ooc.xdc

# XDC: ipshared/VIP/dyract_v1_1/034c9e85/src/dyract.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_dyract_0_1 || ORIG_REF_NAME==dyract_sys_dyract_0_1}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_0/dyract_sys_auto_us_0_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_0/dyract_sys_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_0 || ORIG_REF_NAME==dyract_sys_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_1/dyract_sys_auto_us_1_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_1/dyract_sys_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_1 || ORIG_REF_NAME==dyract_sys_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_auto_pc_0/dyract_sys_auto_pc_0_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_2/dyract_sys_auto_us_2_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_2/dyract_sys_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_2 || ORIG_REF_NAME==dyract_sys_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_3/dyract_sys_auto_us_3_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_3/dyract_sys_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_3 || ORIG_REF_NAME==dyract_sys_auto_us_3}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_4/dyract_sys_auto_us_4_ooc.xdc

# XDC: bd/dyract_sys/ip/dyract_sys_auto_us_4/dyract_sys_auto_us_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dyract_sys_auto_us_4 || ORIG_REF_NAME==dyract_sys_auto_us_4}] {/inst }]/inst ]]

# XDC: bd/dyract_sys/dyract_sys_ooc.xdc
